// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7PpqJG8RKvBx3fpb7Lup7jNh9AnvbXS4',
    appId: '1:1065249041059:web:8a117a714c796295a0ed16',
    messagingSenderId: '1065249041059',
    projectId: 'uas-flutter-86c12',
    authDomain: 'uas-flutter-86c12.firebaseapp.com',
    storageBucket: 'uas-flutter-86c12.appspot.com',
    measurementId: 'G-L95E157L33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOh0amy_DXLLdqKfGNZv7pbSQ09oOLkos',
    appId: '1:1065249041059:android:8f2513300f5d4079a0ed16',
    messagingSenderId: '1065249041059',
    projectId: 'uas-flutter-86c12',
    storageBucket: 'uas-flutter-86c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAykUKG9zSWFiMIC7ke_mAf7HFnkBJpbk',
    appId: '1:1065249041059:ios:eefb3f3727da0150a0ed16',
    messagingSenderId: '1065249041059',
    projectId: 'uas-flutter-86c12',
    storageBucket: 'uas-flutter-86c12.appspot.com',
    iosBundleId: 'com.example.uasFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAykUKG9zSWFiMIC7ke_mAf7HFnkBJpbk',
    appId: '1:1065249041059:ios:eefb3f3727da0150a0ed16',
    messagingSenderId: '1065249041059',
    projectId: 'uas-flutter-86c12',
    storageBucket: 'uas-flutter-86c12.appspot.com',
    iosBundleId: 'com.example.uasFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7PpqJG8RKvBx3fpb7Lup7jNh9AnvbXS4',
    appId: '1:1065249041059:web:7a092be41c5bc711a0ed16',
    messagingSenderId: '1065249041059',
    projectId: 'uas-flutter-86c12',
    authDomain: 'uas-flutter-86c12.firebaseapp.com',
    storageBucket: 'uas-flutter-86c12.appspot.com',
    measurementId: 'G-3G9MF9ZG29',
  );
}
